import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ExchangeCalculator {

	public static void main(String[] args) {
		String input = askForInput();
		ParseInput parseInput = new ParseInput();
		ExchangeCalculator calc = new ExchangeCalculator();
		System.out.println(calc.currencyConvertor(parseInput.getCurrencyPairs(input), parseInput.getAmmount(input)));
	}

	public static String askForInput() {
		System.out.println("Enter what you want to convert. Please not, the format is very strick and it should be as 'How many EURO is 5 PLN'. "
				+ "Currencies supported: EURO USD GBP PLN UAH");
		Scanner sc = new Scanner(System.in);
		String input = sc.nextLine();
		return input;
	}

	public double currencyConvertor(CurrencyPairs currencyPair, double ammount) {
		double ammountConverted = 0;
		switch (currencyPair) {
		case USDPLN:
			ammountConverted = ammount / 4.07;
			break;
		case USDEURO:
			ammountConverted = ammount / 1.57;
			break;
		case USDUAH:
			ammountConverted = ammount / 27.20;
			break;
		case USDGBP:
			ammountConverted = ammount / 0.81;
			break;
		case PLNUSD:
			ammountConverted = ammount / 0.25;
			break;
		case PLNEURO:
			ammountConverted = ammount / 0.23;
			break;
		case PLNUAH:
			ammountConverted = ammount / 6.68;
			break;
		case PLNGBP:
			ammountConverted = ammount / 0.20;
			break;
		case UAHUSD:
			ammountConverted = ammount / 1.57;
			break;
		case UAHPLN:
			ammountConverted = ammount / 0.15;
			break;
		case UAHEURO:
			ammountConverted = ammount / 0.035;
			break;
		case UAHGBP:
			ammountConverted = ammount / 0.030;
			break;
		case GBPUSD:
			ammountConverted = ammount / 1.23;
			break;
		case GBPPLN:
			ammountConverted = ammount / 5.04;
			break;
		case GBPEURO:
			ammountConverted = ammount / 1.17;
			break;
		case GBPUAH:
			ammountConverted = ammount / 33.68;
			break;
		case EUROGBP:
			ammountConverted = ammount / 0.85;
			break;
		case EUROPLN:
			ammountConverted = ammount / 4.31;
			break;
		case EUROUAH:
			ammountConverted = ammount / 28.77;
			break;
		case EUROUSD:
			ammountConverted = ammount / 1.06;
			break;
		}
		return ammountConverted;
	}
}
