/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
	
	@DataProvider(name="currencyPairs")
	public Object[][] currencyPairs(){
		return new Object[][]{
			{CurrencyPairs.EUROGBP, 85d, 100d},
			{CurrencyPairs.EUROPLN, 431d, 100d},
			{CurrencyPairs.EUROUAH, 2877d, 100d},
			{CurrencyPairs.EUROUSD, 106d, 100d},
			{CurrencyPairs.GBPEURO, 117d, 100d},
			{CurrencyPairs.GBPPLN, 504d, 100d},
			{CurrencyPairs.GBPUAH, 3368d, 100d},
			{CurrencyPairs.GBPUSD, 123d, 100d},
			{CurrencyPairs.USDEURO, 157d, 100d},
			{CurrencyPairs.USDGBP, 81d, 100d},
			{CurrencyPairs.USDPLN, 407d, 100d},
			{CurrencyPairs.USDUAH, 2720d, 100d},
			{CurrencyPairs.PLNEURO, 23d, 100d},
			{CurrencyPairs.PLNGBP, 20d, 100d},
			{CurrencyPairs.PLNUAH, 668d, 100d},
			{CurrencyPairs.PLNUSD, 25d, 100d},
			{CurrencyPairs.UAHEURO, 3.50d, 100d  },
			{CurrencyPairs.UAHGBP, 3d, 100d },
			{CurrencyPairs.UAHPLN, 15d, 100d },
			{CurrencyPairs.UAHUSD, 157d, 100d}
		};
	}
	
    @Test(dataProvider="currencyPairs")
    public void checkConvertPairsProperCalculate(CurrencyPairs curPair, double ammount, double expected) {
        ExchangeCalculator classUnderTest = new ExchangeCalculator();
        assertEquals(classUnderTest.currencyConvertor(curPair, ammount), expected);
    }
}
